In [ ]:
from sklearn.decomposition import PCA
import numpy as np

# Example dataset
X = np.array([[2.5, 2.4, 3.5],
              [0.5, 0.7, 0.6],
              [2.2, 2.9, 3.1],
              [1.9, 2.2, 2.7],
              [3.1, 3.0, 3.4]])

# Initialize PCA with the number of components
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)

print(X_reduced)

[[ 0.89224205 -0.38214531]
 [-2.99635754  0.02461119]
 [ 0.7180198   0.25855925]
 [-0.06912356 -0.05578092]
 [ 1.45521926  0.15475579]]


In [ ]:
import pandas as pd
from sklearn.decomposition import PCA

# Load dataset from CSV file
file_path = '/content/data4.csv'  # Replace with the path to your CSV file
df = pd.read_csv(file_path)

# Assuming the dataset has no labels and all columns are features
X = df.values

# Initialize PCA with the number of components
pca = PCA(n_components=2)  # Change the number of components as needed

# Fit and transform the data
X_reduced = pca.fit_transform(X)

# Print the reduced dataset
print(X_reduced)

[[ 0.89224205 -0.38214531]
 [-2.99635754  0.02461119]
 [ 0.7180198   0.25855925]
 [-0.06912356 -0.05578092]
 [ 1.45521926  0.15475579]]


In [ ]:
import pandas as pd
from sklearn.decomposition import PCA

# URL of the dataset (replace with the actual URL where the CSV is hosted)
url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTl187Oc8LJiHZ1890DB44kBlEtYU5aCzQUhZkPP4Gg6TXov8VRJloGNtuiZ31FKML6O-eEEqEZtGna/pub?output=csv'

# Load dataset from the URL
df = pd.read_csv(url)

# Assuming the dataset has no labels and all columns are features
X = df.values

# Initialize PCA with the number of components
pca = PCA(n_components=2)  # Change the number of components as needed

# Fit and transform the data
X_reduced = pca.fit_transform(X)

# Print the reduced dataset
print(X_reduced)

                            UDAIYANETHI 221191101141                            
[[ 0.89224205 -0.38214531]
 [-2.99635754  0.02461119]
 [ 0.7180198   0.25855925]
 [-0.06912356 -0.05578092]
 [ 1.45521926  0.15475579]]
