In [ ]:
import numpy as np
from scipy.stats import chi2_contingency, f_oneway

# ----- Chi-Square Test -----
# Sample Data for Chi-Square Test (Contingency Table)
observed = np.array([[30, 20],
                     [20, 25],
                     [50, 35]])

# Perform the Chi-Square Test
chi2, p_chi2, dof, expected = chi2_contingency(observed)

print("----- Chi-Square Test Results -----")
print(f"Chi-Square Statistic: {chi2}")
print(f"p-value: {p_chi2}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:{expected}")
print(expected)
print("\n")

# ----- ANOVA F-Test -----
# Sample Data for ANOVA F-Test
class1 = [85, 88, 90, 87]
class2 = [78, 82, 79, 85]
class3 = [92, 94, 89, 91]

# Perform the ANOVA F-Test
f_statistic, p_anova = f_oneway(class1, class2, class3)

print("----- ANOVA F-Test Results -----")
print(f"F-Statistic: {f_statistic}")
print(f"p-value: {p_anova}")

----- Chi-Square Test Results -----
Chi-Square Statistic: 3.0176470588235293
p-value: 0.22117002498994276
Degrees of Freedom: 2
Expected Frequencies:{expected}
[[27.77777778 22.22222222]
 [25.         20.        ]
 [47.22222222 37.77777778]]


----- ANOVA F-Test Results -----
F-Statistic: 18.053571428571438
p-value: 0.0007079251736606424


In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, f_oneway


# ----- Chi-Square Test -----
# Load the Chi-Square data from CSV
chi_square_data = pd.read_csv('chi_square_data.csv', index_col=0)

# Convert to numpy array
observed = chi_square_data.to_numpy()

# Perform the Chi-Square Test
chi2, p_chi2, dof, expected = chi2_contingency(observed)

print("----- Chi-Square Test Results -----")
print(f"Chi-Square Statistic: {chi2}")
print(f"p-value: {p_chi2}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print("\n")

# ----- ANOVA F-Test -----
# Load the ANOVA data from CSV
anova_data = pd.read_csv('anova_data.csv')

# Extract data for each class
class1 = anova_data['Class1']
class2 = anova_data['Class2']
class3 = anova_data['Class3']

# Perform the ANOVA F-Test
f_statistic, p_anova = f_oneway(class1, class2, class3)

print("----- ANOVA F-Test Results -----")
print(f"F-Statistic: {f_statistic}")
print(f"p-value: {p_anova}")

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, f_oneway


# Replace these URLs with your actual URLs
chi_square_data_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRF29A23fZvOk9mDFif74CE10HIyjwEFGUiDGa6934sFQQnkRm_5Hm9_CsQuTPV2S7MoRyJcGNN-PB8/pub?output=csv'
anova_data_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSHjE6gORxV85VjN26vJPII84nDKJQogeqv5C5jY9Om8eZJOYzH8V1KTaE6Z89wNPWRLsXub47Skycf/pub?output=csv'

# ----- Chi-Square Test -----
# Load the Chi-Square data from the URL
chi_square_data = pd.read_csv(chi_square_data_url, index_col=0)

# Convert to numpy array
observed = chi_square_data.to_numpy()

# Perform the Chi-Square Test
chi2, p_chi2, dof, expected = chi2_contingency(observed)

print("----- Chi-Square Test Results -----")
print(f"Chi-Square Statistic: {chi2}")
print(f"p-value: {p_chi2}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print("\n")

# ----- ANOVA F-Test -----
# Load the ANOVA data from the URL
anova_data = pd.read_csv(anova_data_url)

# Extract data for each class
class1 = anova_data['Class1']
class2 = anova_data['Class2']
class3 = anova_data['Class3']

# Perform the ANOVA F-Test
f_statistic, p_anova = f_oneway(class1, class2, class3)

print("----- ANOVA F-Test Results -----")
print(f"F-Statistic: {f_statistic}")
print(f"p-value: {p_anova}")

                            UDAIYANETHI 221191101141                            
----- Chi-Square Test Results -----
Chi-Square Statistic: 3.0176470588235293
p-value: 0.22117002498994276
Degrees of Freedom: 2
Expected Frequencies:
[[27.77777778 25.         47.22222222]
 [22.22222222 20.         37.77777778]]


----- ANOVA F-Test Results -----
F-Statistic: 18.053571428571438
p-value: 0.0007079251736606424


In [2]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, f_oneway


# Replace these URLs with your actual URLs
chi_square_data_url = 'https://raw.githubusercontent.com/Ryu0101/PMA/refs/heads/main/data3a.csv'
anova_data_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSHjE6gORxV85VjN26vJPII84nDKJQogeqv5C5jY9Om8eZJOYzH8V1KTaE6Z89wNPWRLsXub47Skycf/pub?output=csv'

# ----- Chi-Square Test -----
# Load the Chi-Square data from the URL
chi_square_data = pd.read_csv(chi_square_data_url, index_col=0)

# Convert to numpy array
observed = chi_square_data.to_numpy()

# Perform the Chi-Square Test
chi2, p_chi2, dof, expected = chi2_contingency(observed)

print("----- Chi-Square Test Results -----")
print(f"Chi-Square Statistic: {chi2}")
print(f"p-value: {p_chi2}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print("\n")

# ----- ANOVA F-Test -----
# Load the ANOVA data from the URL
anova_data = pd.read_csv(anova_data_url)

# Extract data for each class
class1 = anova_data['Class1']
class2 = anova_data['Class2']
class3 = anova_data['Class3']

# Perform the ANOVA F-Test
f_statistic, p_anova = f_oneway(class1, class2, class3)

print("----- ANOVA F-Test Results -----")
print(f"F-Statistic: {f_statistic}")
print(f"p-value: {p_anova}")

----- Chi-Square Test Results -----
Chi-Square Statistic: 3.0176470588235293
p-value: 0.22117002498994276
Degrees of Freedom: 2
Expected Frequencies:
[[27.77777778 25.         47.22222222]
 [22.22222222 20.         37.77777778]]


----- ANOVA F-Test Results -----
F-Statistic: 18.053571428571438
p-value: 0.0007079251736606424
